#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.0.{build}

# branches to build
branches:
  only:
    - master
    - /v\d*\.\d*\.\d*/

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true
#skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
#image: Visual Studio 2017

# environment variables
environment:
  matrix:
    - platform: x86
      msystem: mingw32
      bit: 32bit
    - platform: x64
      msystem: mingw64
      bit: 64bit

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

#---------------------------------#
#        install scripts          #
#---------------------------------#
# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cmd: git submodule update --init --recursive

#---------------------------------#
#       build configuration       #
#---------------------------------#
# to disable automatic builds - use build_script
build: off

# scripts to run before build
before_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
  - cmd: grep '#define APP_VERSION_STR' %APPVEYOR_BUILD_FOLDER%/app/Rajce/Version.h > APP_VERSION
  - cmd: sed -i -e 's/.*"\([0-9\.]*\)".*/\1/' APP_VERSION
  - cmd: set /p APP_VERSION= < APP_VERSION
  - cmd: echo %APP_VERSION%
  - cmd: echo %NUMBER_OF_PROCESSORS%
  - cmd: GenerateCMakeFiles.sh "MINGW"
  - cmd: mkdir build.%MSYSTEM%
  - cmd: cd build.%MSYSTEM%
  - cmd: cmake -G "Unix Makefiles" ..
  - cmd: mingw32-make -j %NUMBER_OF_PROCESSORS%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

# To create a single “zip” artifact with multiple files from different locations you can use 7z in “after build” script which is already available in PATH:
# 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\path\to\bin\*.dll
# Specifying the absolute path here is required to remove paths from archive. However, if you need to preserve paths in the archive use relative paths, like:
# 7z a myapp.zip path\to\bin\*.dll

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - cmd: mv %APPVEYOR_BUILD_FOLDER%\Rajce.upp.tar.bz2 %APPVEYOR_BUILD_FOLDER%\Rajce.upp-%APP_VERSION%.tar.bz2
  - cmd: cp %APPVEYOR_BUILD_FOLDER%\app\Rajce\Copying %APPVEYOR_BUILD_FOLDER%\build.%MSYSTEM%\LICENSE
  - cmd: 7z a rajce-%APP_VERSION%-%BIT%.zip %APPVEYOR_BUILD_FOLDER%\build.%MSYSTEM%\bin\Rajce.exe %APPVEYOR_BUILD_FOLDER%\build.%MSYSTEM%\LICENSE
  - cmd: sha256sum rajce-%APP_VERSION%-%BIT%.zip > rajce-%APP_VERSION%-%BIT%.zip.sha256
  - cmd: sha256sum %APPVEYOR_BUILD_FOLDER%\Rajce.upp-%APP_VERSION%.tar.bz2 > %APPVEYOR_BUILD_FOLDER%\Rajce.upp-%APP_VERSION%.tar.bz2.sha256

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

#---------------------------------#
#       test configuration        #
#---------------------------------#
#To disable test phase completely
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: rajce-*.zip
    name: App
  - path: rajce-*.zip.sha256
    name: AppSha
  - path: Rajce.upp-*.bz2
    name: AppSource
  - path: Rajce.upp-*.bz2.sha256
    name: AppSourceSha

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# provider names are case-sensitive!

# Deploy to GitHub Releases
deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    # description is mandatory. If not specified, GitHub returns 422: Unprocessable entity error.
    description: "$(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n$(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)"
    auth_token:
      secure: /2wk1VbTrLPMDtwW9DAabAjZd4FmAddIENq5eGit+1JxlBCM9JSGmTyFq6Ioo1AeTn2985jFGbKfE+WIW2cnFQ4zyfdduhLH2AloQZw7r2ALTzqomu4acBdHsKI4LBQX
    artifact: /App.*/
    draft: false
    prerelease: false
    on:
#      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only

