#!/bin/bash

#git submodule add https://github.com/CoolmanCZ/upp_cmake.git
#git submodule add https://github.com/CoolmanCZ/ultimatepp.git
git submodule update --init --recursive
#git submodule update --remote

